/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VentasRouteImport } from './routes/ventas'
import { Route as MarcasRouteImport } from './routes/marcas'
import { Route as DevolucionesRouteImport } from './routes/devoluciones'
import { Route as ComprasRouteImport } from './routes/compras'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as CategoriasRouteImport } from './routes/categorias'
import { Route as AlmacenesRouteImport } from './routes/almacenes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArticulosIndexRouteImport } from './routes/articulos/index'
import { Route as ArticulosVariantesRouteImport } from './routes/articulos/variantes'
import { Route as ArticulosFabricantesRouteImport } from './routes/articulos/fabricantes'

const VentasRoute = VentasRouteImport.update({
  id: '/ventas',
  path: '/ventas',
  getParentRoute: () => rootRouteImport,
} as any)
const MarcasRoute = MarcasRouteImport.update({
  id: '/marcas',
  path: '/marcas',
  getParentRoute: () => rootRouteImport,
} as any)
const DevolucionesRoute = DevolucionesRouteImport.update({
  id: '/devoluciones',
  path: '/devoluciones',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprasRoute = ComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasRoute = CategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const AlmacenesRoute = AlmacenesRouteImport.update({
  id: '/almacenes',
  path: '/almacenes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticulosIndexRoute = ArticulosIndexRouteImport.update({
  id: '/articulos/',
  path: '/articulos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticulosVariantesRoute = ArticulosVariantesRouteImport.update({
  id: '/articulos/variantes',
  path: '/articulos/variantes',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticulosFabricantesRoute = ArticulosFabricantesRouteImport.update({
  id: '/articulos/fabricantes',
  path: '/articulos/fabricantes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/almacenes': typeof AlmacenesRoute
  '/categorias': typeof CategoriasRoute
  '/clientes': typeof ClientesRoute
  '/compras': typeof ComprasRoute
  '/devoluciones': typeof DevolucionesRoute
  '/marcas': typeof MarcasRoute
  '/ventas': typeof VentasRoute
  '/articulos/fabricantes': typeof ArticulosFabricantesRoute
  '/articulos/variantes': typeof ArticulosVariantesRoute
  '/articulos/': typeof ArticulosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/almacenes': typeof AlmacenesRoute
  '/categorias': typeof CategoriasRoute
  '/clientes': typeof ClientesRoute
  '/compras': typeof ComprasRoute
  '/devoluciones': typeof DevolucionesRoute
  '/marcas': typeof MarcasRoute
  '/ventas': typeof VentasRoute
  '/articulos/fabricantes': typeof ArticulosFabricantesRoute
  '/articulos/variantes': typeof ArticulosVariantesRoute
  '/articulos': typeof ArticulosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/almacenes': typeof AlmacenesRoute
  '/categorias': typeof CategoriasRoute
  '/clientes': typeof ClientesRoute
  '/compras': typeof ComprasRoute
  '/devoluciones': typeof DevolucionesRoute
  '/marcas': typeof MarcasRoute
  '/ventas': typeof VentasRoute
  '/articulos/fabricantes': typeof ArticulosFabricantesRoute
  '/articulos/variantes': typeof ArticulosVariantesRoute
  '/articulos/': typeof ArticulosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/almacenes'
    | '/categorias'
    | '/clientes'
    | '/compras'
    | '/devoluciones'
    | '/marcas'
    | '/ventas'
    | '/articulos/fabricantes'
    | '/articulos/variantes'
    | '/articulos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/almacenes'
    | '/categorias'
    | '/clientes'
    | '/compras'
    | '/devoluciones'
    | '/marcas'
    | '/ventas'
    | '/articulos/fabricantes'
    | '/articulos/variantes'
    | '/articulos'
  id:
    | '__root__'
    | '/'
    | '/almacenes'
    | '/categorias'
    | '/clientes'
    | '/compras'
    | '/devoluciones'
    | '/marcas'
    | '/ventas'
    | '/articulos/fabricantes'
    | '/articulos/variantes'
    | '/articulos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlmacenesRoute: typeof AlmacenesRoute
  CategoriasRoute: typeof CategoriasRoute
  ClientesRoute: typeof ClientesRoute
  ComprasRoute: typeof ComprasRoute
  DevolucionesRoute: typeof DevolucionesRoute
  MarcasRoute: typeof MarcasRoute
  VentasRoute: typeof VentasRoute
  ArticulosFabricantesRoute: typeof ArticulosFabricantesRoute
  ArticulosVariantesRoute: typeof ArticulosVariantesRoute
  ArticulosIndexRoute: typeof ArticulosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ventas': {
      id: '/ventas'
      path: '/ventas'
      fullPath: '/ventas'
      preLoaderRoute: typeof VentasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marcas': {
      id: '/marcas'
      path: '/marcas'
      fullPath: '/marcas'
      preLoaderRoute: typeof MarcasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devoluciones': {
      id: '/devoluciones'
      path: '/devoluciones'
      fullPath: '/devoluciones'
      preLoaderRoute: typeof DevolucionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compras': {
      id: '/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof ComprasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias': {
      id: '/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof CategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/almacenes': {
      id: '/almacenes'
      path: '/almacenes'
      fullPath: '/almacenes'
      preLoaderRoute: typeof AlmacenesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articulos/': {
      id: '/articulos/'
      path: '/articulos'
      fullPath: '/articulos/'
      preLoaderRoute: typeof ArticulosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articulos/variantes': {
      id: '/articulos/variantes'
      path: '/articulos/variantes'
      fullPath: '/articulos/variantes'
      preLoaderRoute: typeof ArticulosVariantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articulos/fabricantes': {
      id: '/articulos/fabricantes'
      path: '/articulos/fabricantes'
      fullPath: '/articulos/fabricantes'
      preLoaderRoute: typeof ArticulosFabricantesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlmacenesRoute: AlmacenesRoute,
  CategoriasRoute: CategoriasRoute,
  ClientesRoute: ClientesRoute,
  ComprasRoute: ComprasRoute,
  DevolucionesRoute: DevolucionesRoute,
  MarcasRoute: MarcasRoute,
  VentasRoute: VentasRoute,
  ArticulosFabricantesRoute: ArticulosFabricantesRoute,
  ArticulosVariantesRoute: ArticulosVariantesRoute,
  ArticulosIndexRoute: ArticulosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
