/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MarcasRouteImport } from './routes/marcas'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DevolucionesRouteImport } from './routes/devoluciones'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as CategoriasRouteImport } from './routes/categorias'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VentasIndexRouteImport } from './routes/ventas/index'
import { Route as ReportesIndexRouteImport } from './routes/reportes/index'
import { Route as ComprasIndexRouteImport } from './routes/compras/index'
import { Route as ArticulosIndexRouteImport } from './routes/articulos/index'
import { Route as AlmacenesIndexRouteImport } from './routes/almacenes/index'
import { Route as VentasCrearRouteImport } from './routes/ventas/crear'
import { Route as ComprasProveedoresRouteImport } from './routes/compras/proveedores'
import { Route as ComprasCrearRouteImport } from './routes/compras/crear'
import { Route as ArticulosVariantesRouteImport } from './routes/articulos/variantes'
import { Route as ArticulosFabricantesRouteImport } from './routes/articulos/fabricantes'
import { Route as AlmacenesConsultaRouteImport } from './routes/almacenes/consulta'

const MarcasRoute = MarcasRouteImport.update({
  id: '/marcas',
  path: '/marcas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DevolucionesRoute = DevolucionesRouteImport.update({
  id: '/devoluciones',
  path: '/devoluciones',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasRoute = CategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VentasIndexRoute = VentasIndexRouteImport.update({
  id: '/ventas/',
  path: '/ventas/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportesIndexRoute = ReportesIndexRouteImport.update({
  id: '/reportes/',
  path: '/reportes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprasIndexRoute = ComprasIndexRouteImport.update({
  id: '/compras/',
  path: '/compras/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticulosIndexRoute = ArticulosIndexRouteImport.update({
  id: '/articulos/',
  path: '/articulos/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlmacenesIndexRoute = AlmacenesIndexRouteImport.update({
  id: '/almacenes/',
  path: '/almacenes/',
  getParentRoute: () => rootRouteImport,
} as any)
const VentasCrearRoute = VentasCrearRouteImport.update({
  id: '/ventas/crear',
  path: '/ventas/crear',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprasProveedoresRoute = ComprasProveedoresRouteImport.update({
  id: '/compras/proveedores',
  path: '/compras/proveedores',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprasCrearRoute = ComprasCrearRouteImport.update({
  id: '/compras/crear',
  path: '/compras/crear',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticulosVariantesRoute = ArticulosVariantesRouteImport.update({
  id: '/articulos/variantes',
  path: '/articulos/variantes',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticulosFabricantesRoute = ArticulosFabricantesRouteImport.update({
  id: '/articulos/fabricantes',
  path: '/articulos/fabricantes',
  getParentRoute: () => rootRouteImport,
} as any)
const AlmacenesConsultaRoute = AlmacenesConsultaRouteImport.update({
  id: '/almacenes/consulta',
  path: '/almacenes/consulta',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/categorias': typeof CategoriasRoute
  '/clientes': typeof ClientesRoute
  '/devoluciones': typeof DevolucionesRoute
  '/login': typeof LoginRoute
  '/marcas': typeof MarcasRoute
  '/almacenes/consulta': typeof AlmacenesConsultaRoute
  '/articulos/fabricantes': typeof ArticulosFabricantesRoute
  '/articulos/variantes': typeof ArticulosVariantesRoute
  '/compras/crear': typeof ComprasCrearRoute
  '/compras/proveedores': typeof ComprasProveedoresRoute
  '/ventas/crear': typeof VentasCrearRoute
  '/almacenes/': typeof AlmacenesIndexRoute
  '/articulos/': typeof ArticulosIndexRoute
  '/compras/': typeof ComprasIndexRoute
  '/reportes/': typeof ReportesIndexRoute
  '/ventas/': typeof VentasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categorias': typeof CategoriasRoute
  '/clientes': typeof ClientesRoute
  '/devoluciones': typeof DevolucionesRoute
  '/login': typeof LoginRoute
  '/marcas': typeof MarcasRoute
  '/almacenes/consulta': typeof AlmacenesConsultaRoute
  '/articulos/fabricantes': typeof ArticulosFabricantesRoute
  '/articulos/variantes': typeof ArticulosVariantesRoute
  '/compras/crear': typeof ComprasCrearRoute
  '/compras/proveedores': typeof ComprasProveedoresRoute
  '/ventas/crear': typeof VentasCrearRoute
  '/almacenes': typeof AlmacenesIndexRoute
  '/articulos': typeof ArticulosIndexRoute
  '/compras': typeof ComprasIndexRoute
  '/reportes': typeof ReportesIndexRoute
  '/ventas': typeof VentasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/categorias': typeof CategoriasRoute
  '/clientes': typeof ClientesRoute
  '/devoluciones': typeof DevolucionesRoute
  '/login': typeof LoginRoute
  '/marcas': typeof MarcasRoute
  '/almacenes/consulta': typeof AlmacenesConsultaRoute
  '/articulos/fabricantes': typeof ArticulosFabricantesRoute
  '/articulos/variantes': typeof ArticulosVariantesRoute
  '/compras/crear': typeof ComprasCrearRoute
  '/compras/proveedores': typeof ComprasProveedoresRoute
  '/ventas/crear': typeof VentasCrearRoute
  '/almacenes/': typeof AlmacenesIndexRoute
  '/articulos/': typeof ArticulosIndexRoute
  '/compras/': typeof ComprasIndexRoute
  '/reportes/': typeof ReportesIndexRoute
  '/ventas/': typeof VentasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/categorias'
    | '/clientes'
    | '/devoluciones'
    | '/login'
    | '/marcas'
    | '/almacenes/consulta'
    | '/articulos/fabricantes'
    | '/articulos/variantes'
    | '/compras/crear'
    | '/compras/proveedores'
    | '/ventas/crear'
    | '/almacenes/'
    | '/articulos/'
    | '/compras/'
    | '/reportes/'
    | '/ventas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/categorias'
    | '/clientes'
    | '/devoluciones'
    | '/login'
    | '/marcas'
    | '/almacenes/consulta'
    | '/articulos/fabricantes'
    | '/articulos/variantes'
    | '/compras/crear'
    | '/compras/proveedores'
    | '/ventas/crear'
    | '/almacenes'
    | '/articulos'
    | '/compras'
    | '/reportes'
    | '/ventas'
  id:
    | '__root__'
    | '/'
    | '/categorias'
    | '/clientes'
    | '/devoluciones'
    | '/login'
    | '/marcas'
    | '/almacenes/consulta'
    | '/articulos/fabricantes'
    | '/articulos/variantes'
    | '/compras/crear'
    | '/compras/proveedores'
    | '/ventas/crear'
    | '/almacenes/'
    | '/articulos/'
    | '/compras/'
    | '/reportes/'
    | '/ventas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoriasRoute: typeof CategoriasRoute
  ClientesRoute: typeof ClientesRoute
  DevolucionesRoute: typeof DevolucionesRoute
  LoginRoute: typeof LoginRoute
  MarcasRoute: typeof MarcasRoute
  AlmacenesConsultaRoute: typeof AlmacenesConsultaRoute
  ArticulosFabricantesRoute: typeof ArticulosFabricantesRoute
  ArticulosVariantesRoute: typeof ArticulosVariantesRoute
  ComprasCrearRoute: typeof ComprasCrearRoute
  ComprasProveedoresRoute: typeof ComprasProveedoresRoute
  VentasCrearRoute: typeof VentasCrearRoute
  AlmacenesIndexRoute: typeof AlmacenesIndexRoute
  ArticulosIndexRoute: typeof ArticulosIndexRoute
  ComprasIndexRoute: typeof ComprasIndexRoute
  ReportesIndexRoute: typeof ReportesIndexRoute
  VentasIndexRoute: typeof VentasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/marcas': {
      id: '/marcas'
      path: '/marcas'
      fullPath: '/marcas'
      preLoaderRoute: typeof MarcasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devoluciones': {
      id: '/devoluciones'
      path: '/devoluciones'
      fullPath: '/devoluciones'
      preLoaderRoute: typeof DevolucionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias': {
      id: '/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof CategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ventas/': {
      id: '/ventas/'
      path: '/ventas'
      fullPath: '/ventas/'
      preLoaderRoute: typeof VentasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportes/': {
      id: '/reportes/'
      path: '/reportes'
      fullPath: '/reportes/'
      preLoaderRoute: typeof ReportesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compras/': {
      id: '/compras/'
      path: '/compras'
      fullPath: '/compras/'
      preLoaderRoute: typeof ComprasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articulos/': {
      id: '/articulos/'
      path: '/articulos'
      fullPath: '/articulos/'
      preLoaderRoute: typeof ArticulosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/almacenes/': {
      id: '/almacenes/'
      path: '/almacenes'
      fullPath: '/almacenes/'
      preLoaderRoute: typeof AlmacenesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ventas/crear': {
      id: '/ventas/crear'
      path: '/ventas/crear'
      fullPath: '/ventas/crear'
      preLoaderRoute: typeof VentasCrearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compras/proveedores': {
      id: '/compras/proveedores'
      path: '/compras/proveedores'
      fullPath: '/compras/proveedores'
      preLoaderRoute: typeof ComprasProveedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compras/crear': {
      id: '/compras/crear'
      path: '/compras/crear'
      fullPath: '/compras/crear'
      preLoaderRoute: typeof ComprasCrearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articulos/variantes': {
      id: '/articulos/variantes'
      path: '/articulos/variantes'
      fullPath: '/articulos/variantes'
      preLoaderRoute: typeof ArticulosVariantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articulos/fabricantes': {
      id: '/articulos/fabricantes'
      path: '/articulos/fabricantes'
      fullPath: '/articulos/fabricantes'
      preLoaderRoute: typeof ArticulosFabricantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/almacenes/consulta': {
      id: '/almacenes/consulta'
      path: '/almacenes/consulta'
      fullPath: '/almacenes/consulta'
      preLoaderRoute: typeof AlmacenesConsultaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoriasRoute: CategoriasRoute,
  ClientesRoute: ClientesRoute,
  DevolucionesRoute: DevolucionesRoute,
  LoginRoute: LoginRoute,
  MarcasRoute: MarcasRoute,
  AlmacenesConsultaRoute: AlmacenesConsultaRoute,
  ArticulosFabricantesRoute: ArticulosFabricantesRoute,
  ArticulosVariantesRoute: ArticulosVariantesRoute,
  ComprasCrearRoute: ComprasCrearRoute,
  ComprasProveedoresRoute: ComprasProveedoresRoute,
  VentasCrearRoute: VentasCrearRoute,
  AlmacenesIndexRoute: AlmacenesIndexRoute,
  ArticulosIndexRoute: ArticulosIndexRoute,
  ComprasIndexRoute: ComprasIndexRoute,
  ReportesIndexRoute: ReportesIndexRoute,
  VentasIndexRoute: VentasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
